### ISSUE TITLE
Compatibility with pre-WatchKit Xcode

### ISSUE THREAD

**Issue by iMstr** [nomad/shenzhen#263] opened 2015-05-04 17:28 UTC
Everything worked just fine with Xcode 6.0.1 till the latest update my builds break because WatchKit is missing, which is normal in 6.0.1.

error: No such file or directory - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/Library/Application Support/WatchKit/WK. Use --trace to view backtrace

**Comment by CraigSiemens** [comment] 2015-05-06 15:08
I ran into a similar issue with WatchKit where a binary I uploaded to TestFlight was rejected for "Invalid WatchKit Support" which is odd since my app doesn't support WatchKit.

It's probably caused by the changes in 6d0c9cc2. I went back to using 0.14.0 and it works fine.

**Comment by iMstr** [comment] 2015-05-06 15:14
Did the same, there seems to be a pull request to path it: https://github.com/nomad/shenzhen/pull/264

**Comment by 4chanmoot** [comment] 2015-05-08 01:18
+1 to please merge this asap. I'd rather not switch to a totally new tool like fastlane just to work around a bug :)

**Comment by CraigSiemens** [comment] 2015-05-08 01:28
FYI fastane uses shenzhen though it is set to use v0.14.0 to deal with this issue.

**Comment by KrauseFx** [comment] 2015-05-08 08:34
@4chanmoot `fastlane` actually uses `shenzhen` for building by default :wink:

**Comment by KrauseFx** [comment] 2015-05-08 10:17
Current status is available [here](https://github.com/nomad/shenzhen/pull/264#issuecomment-100183533)

**Comment by rhaining** [comment] 2015-05-14 14:47
:+1: on this

**Comment by mattt** [comment] 2015-05-19 13:01
Fixed by #264.

**Closed by mattt** 2015-05-19 13:01 UTC
