### ISSUE TITLE
TestFlightApp.com shutting down on 2/26/2015.  

### ISSUE THREAD

**Issue by DanCodez** [nomad/shenzhen#202] opened 2015-01-29 22:07 UTC
Hi,

TestFlightApp.com is shutting down and being replaced by Apple's TestFlight (available inside iTunes Connect) on 2/16/2015.

That's less than a month away.   Are there any plans to support the new TestFlight in shenzhen ?

Thanks!

**Comment by irons** [comment] 2015-01-29 22:36
In my opinion, you should consider moving to HockeyApp. 

Even if it were straightforward to automate a deployment through iTunes Connect Testflight, it serves a purpose that overlaps almost not at all with testflightapp.com. iTC Testflight by design provides less control over build deployment, with best-case scenarios for getting a build out in the 20-45 minute range, and 1-2 day delays every time you change your version number or get unlucky.

Building that automation will not be straightforward. After you upload the binary to Apple it sits in "processing" limbo for somewhere between 10 minutes and half an hour (in pathological cases, several hours). A tool to deploy it will then have to scrape the website to pick out the build number to submit to beta app review, fill out a form with about ten required fields, and navigate additional modal questions about encryption and export control, which could change at any time. Once that's done, the tool has to identify whether the app has been made available for beta distribution or is still waiting in review, and if it is available, it can be released with yet another step. Determining how to best expose this flow to automation is non-trivial work, especially since placing a new version number in review automatically rescinds beta availability of earlier versions, which is effectively data loss.

This doesn't even address the question of determining which users should receive access, something that testflightapp.com and Hockey both formalize through APIs. Apple's controls don't current provide for any user grouping, and making changes is fairly painstaking even in the web interface.

We depend on HockeyApp for all internal beta distribution until late-stage testing, at which point it is helpful to take advantage of UDID-free distribution to a wider group of stakeholders and testers. But we're a long way off from automating that deployment, and I don't expect that to change in a hurry.

**Comment by KrauseFx** [comment] 2015-01-29 23:18
`shenzhen` will probably just remove the `TestFlight` integration as it is now. Instead you should probably switch to HockeyApp or Crashlytics Beta as @irons mentioned.

In case you really want to use the new TestFlight, you can use [deliver](https://github.com/KrauseFx/deliver), which will also control the iTunes Connect frontend to send the new version to the beta testers.

**Comment by joemasilotti** [comment] 2015-01-29 23:22
Also note that shenzhen already supports automated build uploads to iTunes Connect from PR #159.

**Comment by KrauseFx** [comment] 2015-01-29 23:24
@joemasilotti Good point, almost forgot, this is already implemented :+1:

**Comment by mfirry** [comment] 2015-01-31 15:00
Is it possible to add new beta testers with shenzhen?

**Comment by KrauseFx** [comment] 2015-01-31 15:01
@mfirry not but there is [testflight_invite](https://github.com/Donohue/testflight_invite) to do that.

**Comment by AlexPrinceton** [comment] 2015-02-16 11:46
Oh, great. TestFlight doesn't work well since it was bought by Apple. They discontinued an Android support a year ago, and moreover, it is shutting down the whole testing services now. But problem is your app must comply with the full App Store Guidelines before the start testing process. So, what should the regular QAs do with enterprise apps, that is not supported in iTunes Connect? 
We have to search for a substitutes such as Apphance, Crashlytics or Ubertesters. Inter alia, the last one offers a convenient bug-submission tool, which supports both Android and iOS 6 (and up). Take a look on their pros and cons - http://blog.ubertesters.com/beta-testing-enterprise-apps-without-appstore-review/

**Comment by mfirry** [comment] 2015-02-16 12:49
testflight_invite was exactly what I needed. Thanks @KrauseFx

**Comment by mattt** [comment] 2015-03-06 14:38
As of 2015-02-26, Shenzhen has removed all TestFlight integration.

**Closed by mattt** 2015-03-06 14:38 UTC
